"""Emojis."""
import emoji
import random


FRIDAY_EMOJIS = [
    ":heart_eyes:",
    ":satisfied:",
    ":wink:",
    ":stuck_out_tongue_winking_eye:",
    ":stuck_out_tongue_closed_eyes:",
    ":sunglasses:",
    ":relieved:",
    ":satisfied:",
    ":grin:",
    ":scream:",
    ":smiling_imp:",
    ":green_heart:",
    ":purple_heart:",
    ":sparkling_heart:",
    ":sparkles:",
    ":dizzy:",
    ":boom:",
    ":fire:",
    ":punch:",
    ":fist:",
    ":v:",
    ":point_down:",
    ":raised_hands:",
    ":pray:",
    ":clap:",
    ":muscle:",
    ":dancer:",
    ":dancers:",
    ":ok_woman:",
    ":massage:",
    ":speak_no_evil:",
    ":see_no_evil:",
    ":eyes:",
    ":tongue:",
    ":zap:",
    ":panda_face:",
    ":hatched_chick:",
    ":gift_heart:",
    ":fireworks:",
    ":sparkler:",
    ":ghost:",
    ":gift:",
    ":no_bell:",
    ":balloon:",
    ":mute:",
    ":loudspeaker:",
    ":money_with_wings:",
    ":bomb:",
    ":space_invader:",
    ":video_game:",
    ":dart:",
    ":headphones:",
    ":guitar:",
    ":beer:",
    ":beers:",
    ":cocktail:",
    ":tropical_dring:",
    ":wine_glass:",
    ":pizza:",
    ":hamburger:",
    ":fries:",
    ":watermelon:",
    ":eggplant:",
    ":love_hotel:",
    ":sunrise:",
    ":sunrise_over_mountains:",
    ":stars:",
    ":rainbow:",
    ":rocket:",
    ":100:",
]


def get_random_friday_emoji():
    """Get a random rendered friday emoji."""
    random_emoji = random.choice(FRIDAY_EMOJIS)
    return emoji.emojize(random_emoji, use_aliases=True)
