name: deploy to lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy_source:
    name: deploy to aws lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: zip source code
        uses: papeloto/action-zip@v1
        with:
          files: viernes/app.py viernes/emojis.py viernes/twitter.py viernes/settings.py
          dest: ./viernes.zip

      - name: deploy to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: por-suerte-es-viernes
          zip_file: ./viernes.zip
